### PR TITLE
Added Crucible Overlay, Tools action/heat overlay, Lava/waterfall prediction overlay, Border highlighting

### PR DESCRIPTION
**Pull request by TheLouisHong**
- Added crucible content and alloy quality calculation and overlay 
- Added tools action/heat status overlay
- Added lava/waterfall action prediction and overlay 
- Added border highlighting

Other changes:
- Includes logical reorganization of the code base
- Added and applied checkstyle.xml from runelite/runelite for code style consistency
- Rewrote readme. Added images/gifs.

Crucible Alloy Quality (also, border highlight)   | Heating/Cooling Prediction
:-------------------------:|:-------------------------:
 |

Low/High Heat Warning (also, tools info overlay) | 
:-------------------------:|
|

# Config Panel
config panel

### CODE REVIEW

**Comment by pwatts6060** [comment]
https://github.com/Toofifty/easy-giantsfoundry/assets/30028569/deda2626-0567-45e3-a39f-7421df4135e2

Here you can see it added an extra dunk that wasn't needed. Maybe the acceleration of the temperature change the more dunks you do isn't accounted for?

**Comment by pwatts6060** [comment]
The "Highlight Alpha" config name suggests that it applies to both the border and the clickbox option but it only applies to the border. Either make it apply to both or rename it to "Border Alpha".

**Comment by pwatts6060** [comment]
EastGiantsFoundryState.java you can get rid of the commented out code with parseCrucibleText etc
and same file line 41 this method is not called and can be deleted:
	public int getBarCount()
	{
		return client.getVarbitValue(VARBIT_STEEL_COUNT);
	}

**Comment by pwatts6060** [comment]
image
I would floor this and cast as an integer for display to the player both in game chat and on the crucible overlay

**Comment by TheLouisHong** [comment]
> EastGiantsFoundryState.java you can get rid of the commented out code with parseCrucibleText etc and same file line 41 this method is not called and can be deleted: public int getBarCount() { return client.getVarbitValue(VARBIT_STEEL_COUNT); }



> The "Highlight Alpha" config name suggests that it applies to both the border and the clickbox option but it only applies to the border. Either make it apply to both or rename it to "Border Alpha".

done!  @pwatts6060

**Pull request merged**
